### ISSUE TITLE
How do you actually install a uber egg offline ? 

### ISSUE THREAD

**Issue by rmarou** [alekseyig/PyAssembly#3] opened 2020-02-21 11:36 UTC
I tried using : `easy_install my_package.egg` or `easy_install my_package.egg --find-links `easy_install my_package.egg` 
Without any success.. 

I am kind of giving up on this approach and moving to : generating wheels packaging them, unzip and then install all of them..

**Comment by alekseyig** [comment] 2020-02-21 16:58
@maru-podmast Strange, i will take a look

**Comment by alekseyig** [comment] 2020-02-21 18:42
@maru-podmast i tried to install the egg, produced by pyassembly and it worked for me. Well, not 100%, though. 
The problem is that for whatever reasons `easy_install` tries to find the package on PyPi and fails, because the egg is not published there. However, the package itself is got installed and all its dependencies. So, i would say you can ignore that annoying behavior of `easy_install`.
What kind of error do you get/see when you run your  `easy_install my_package.egg`

**Comment by alekseyig** [comment] 2020-09-14 14:58
@maru-podmast, i am closing this one

**Closed as completed** 2020-09-14 14:58 UTC

**Comment by alekseyig** [comment] 2020-09-16 04:10
@maru-podmast, have you tried to create the zip pyassembly file and use `pip install <fat-file-name>.zip`. let me know if it helped.

**Comment by maru-tw** [comment] 2020-09-16 20:35
`pip install <fat-file-name>.zip` did work indeed for me. No idea why I didn't try it before. 
After I opened the issue, I ended up going a different route anyway.. 
Thanks @alekseyig for thorough investigation 💯
